[phases.setup]
nixPkgs = ['python39', 'nodejs', 'postgresql']

[phases.install]
cmds = [
  'cd backend && pip install -r requirements.txt',
  'cd ../frontend && npm install'
]

[start]
cmd = 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT' 