[phases.setup]
nixPkgs = ['python39', 'nodejs', 'postgresql', 'curl']

[phases.install]
cmds = [
  'cd backend && pip install --no-cache-dir -r requirements.txt',
  'cd ../frontend && npm install --legacy-peer-deps'
]

[phases.build]
cmds = ['cd frontend && npm run build']

[start]
cmd = 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT' 