[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"

[[services]]
name = "backend"
image = "patronix9345/erp-backend:latest"
envVars = [
  { key = "POSTGRES_USER", value = "postgres" },
  { key = "POSTGRES_PASSWORD", value = "postgres" },
  { key = "POSTGRES_SERVER", value = "db" },
  { key = "POSTGRES_PORT", value = "5432" },
  { key = "POSTGRES_DB", value = "erp_db" },
  { key = "ALLOWED_ORIGINS", value = "*" }
]

[[services]]
name = "frontend"
image = "patronix9345/erp-frontend:latest"
envVars = [
  { key = "VITE_API_URL", value = "https://api.your-railway-app.com" }
]

[[services]]
name = "db"
image = "postgres:15"
envVars = [
  { key = "POSTGRES_USER", value = "postgres" },
  { key = "POSTGRES_PASSWORD", value = "postgres" },
  { key = "POSTGRES_DB", value = "erp_db" }
] 